services:
  keycloak:
    image: procube/keycloak-passwordless
    environment:
      KC_DB_URL: jdbc:mysql://mysql/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: password
      OIDC_CLIENT_SECRET: 123456
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  oidc:
    image: procube/nginx-oidc
    ports:
      - "8080:80"
    environment:
      OIDC_CLIENT_ID: keycloak
      OIDC_CLIENT_SECRET: 123456
      OIDC_ISSUER: http://keycloak:8080/realms/develop
      OIDC_AUTH_ENDPOINT: http://keycloak:8080/realms/develop/protocol/openid-connect/auth
      OIDC_LOGOUT_ENDPOINT: http://keycloak:8080/realms/develop/protocol/openid-connect/logout
      OIDC_TOKEN_ENDPOINT: http://keycloak:8080/realms/develop/protocol/openid-connect/token
      OIDC_USER_INFO_ENDPOINT: http://keycloak:8080/realms/develop/protocol/openid-connect/userinfo
      OIDC_JWT_GEN_KEY: 654321
    volumes:
      - ./templates:/etc/nginx/templates
  httpd:
    image: httpd
